openapi: 3.2.0
info:
  title: AB2D Capabilities API
  description: This API Provides Part A (Hospital Insurance) & B (Medical Insurance) claim data to Part D (Prescription Drug Benefit) sponsors.
servers:
- url: https://sandbox.ab2d.cms.gov
  description: Generated server url
security:
- bearerAuth: []
tags:
- name: Capabilities
  description: Provide the standard required FHIR capability statement
paths:
  /api/v3/fhir/metadata:
    get:
      tags:
      - Capabilities
      summary: Request the FHIR capability statement detailing what operations this API…
      operationId: capabilityStatement
      responses:
        '200':
          description: A JSON FHIR capability statement matching  http://hl7.org/fhir/capabilitystatement.html
          content:
            application/json:
              schema:
                type: string
  /api/v2/fhir/metadata:
    get:
      tags:
      - Capabilities
      summary: Request the FHIR capability statement detailing what operations this API…
      operationId: capabilityStatement_1
      responses:
        '200':
          description: A JSON FHIR capability statement matching  http://hl7.org/fhir/capabilitystatement.html
          content:
            application/json:
              schema:
                type: string
components:
  securitySchemes:
    bearerAuth:
      type: http
      name: bearerAuth
      scheme: bearer
      bearerFormat: JWT
