openapi: 3.2.0
info:
  title: AB2D Health Health API
  description: This API Provides Part A (Hospital Insurance) & B (Medical Insurance) claim data to Part D (Prescription Drug Benefit) sponsors.
servers:
- url: https://sandbox.ab2d.cms.gov
  description: Generated server url
security:
- bearerAuth: []
tags:
- name: health-api
paths:
  /health:
    get:
      tags:
      - health-api
      operationId: getHealth
      responses:
        '200':
          description: OK
      summary: Get health
      x-summary-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      name: bearerAuth
      scheme: bearer
      bearerFormat: JWT
